/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Confirmations {
  createdAt: Generated<Timestamp>
  id: Generated<string>
  name: string
}

export interface Invites {
  confirmedAt: Timestamp | null
  createdAt: Generated<Timestamp>
  id: Generated<string>
  name: string
}

export interface Sessions {
  createdAt: Generated<Timestamp>
  id: Generated<string>
}

export interface SongRequests {
  createdAt: Generated<Timestamp>
  id: Generated<string>
  link: string
  name: string
  thumbnail: string
}

export interface DB {
  confirmations: Confirmations
  invites: Invites
  sessions: Sessions
  songRequests: SongRequests
}
