import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'

import Nav from '@/components/Nav'

import '@/assets/app.scss'
import moneta from '@/assets/fonts/moneta'
import '@/assets/reset.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="pt-br">
    <body className={moneta.variable}>
      <Nav />
      {children}
    </body>
  </html>
)

export default RootLayout
