import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { PropsWithChildren } from 'react'

import Footer from '@/components/Footer'
import Nav from '@/components/Nav'

import '@/assets/app.scss'
import moneta from '@/assets/fonts/moneta'
import '@/assets/reset.scss'

const LoginModal = dynamic(() => import('@/components/LoginModal'))

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="pt-br">
    <body className={moneta.variable}>
      <Nav />
      {children}
      <Footer />
      <LoginModal />
    </body>
  </html>
)

export default RootLayout
